# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0002_auto_20171121_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='geotargeting',
            field=models.NullBooleanField(),
        ),
    ]
