# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0003_auto_20171121_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='coupon_iframe_denied',
            field=models.NullBooleanField(),
        ),
    ]
