# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0007_auto_20171121_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='cr_trend',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
