# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0008_auto_20171121_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaign',
            name='ecpc',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='advcampaign',
            name='ecpc_trend',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='advcampaign',
            name='rate_of_approve',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
