# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0009_auto_20171121_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaign',
            name='more_rules',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='rate_of_approve',
            field=models.SmallIntegerField(null=True),
        ),
    ]
