# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0011_auto_20171121_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaign',
            name='activation_date',
            field=models.DateTimeField(null=True),
        ),
    ]
