# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0012_advcampaign_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaign',
            name='modified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
