# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0013_advcampaign_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaign',
            name='avg_hold_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advcampaign',
            name='denynewwms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advcampaign',
            name='goto_cookie_lifetime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
