# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0014_auto_20171121_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='avg_hold_time',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='denynewwms',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='goto_cookie_lifetime',
            field=models.SmallIntegerField(null=True),
        ),
    ]
