# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0015_auto_20171121_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaign',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
