# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0016_advcampaign_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='cr',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='cr_trend',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
