# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0018_auto_20171121_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='cr',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
