# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0019_auto_20171121_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='cr_trend',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='ecpc',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='ecpc_trend',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
