# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0020_auto_20171121_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvCampaignRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='advcampaign',
            name='action_type',
            field=models.IntegerField(choices=[(1, 'lead'), (2, 'sale')], null=True),
        ),
    ]
