# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0021_auto_20171121_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvCampaignRegion',
            new_name='MetaRegion',
        ),
    ]
