# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0022_auto_20171121_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('min_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=100)),
                ('sign', models.CharField(max_length=5)),
            ],
        ),
    ]
