# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0024_auto_20171121_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacurrency',
            name='min_sum',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
