# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0028_auto_20171127_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaign',
            name='traffics',
            field=models.ManyToManyField(to='admintad.MetaTraffic'),
        ),
    ]
