# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0029_advcampaign_traffics'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaign',
            name='categories',
            field=models.ManyToManyField(to='admintad.MetaCategory'),
        ),
    ]
