# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0031_auto_20171127_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_size', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'lead'), (2, 'sale')], null=True)),
            ],
            options={
                'verbose_name_plural': 'Meta action',
            },
        ),
    ]
