# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0032_metaaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaaction',
            name='payment_size',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
