# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0033_auto_20171127_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaign',
            name='actions',
            field=models.ManyToManyField(to='admintad.MetaAction'),
        ),
    ]
