# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0036_auto_20171127_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='image',
            field=models.URLField(max_length=251, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='short_name',
            field=models.CharField(max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='site_url',
            field=models.URLField(max_length=252, null=True, verbose_name='Site URL'),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Status'),
        ),
    ]
