# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0037_auto_20171127_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='site_url',
            field=models.URLField(max_length=400, null=True, verbose_name='Site URL'),
        ),
    ]
