# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0038_auto_20171127_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaign',
            name='image',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='short_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaign',
            name='status',
            field=models.CharField(max_length=250, null=True, verbose_name='Status'),
        ),
    ]
