# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0039_auto_20171127_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvCampaignSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('image', models.URLField(max_length=250, null=True)),
                ('status', models.CharField(max_length=250, null=True, verbose_name='Status')),
                ('connection_status', models.IntegerField(choices=[(1, 'active'), (2, 'pending'), (2, 'declined')], null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(null=True)),
                ('raw_description', models.TextField(null=True)),
                ('site_url', models.URLField(max_length=400, null=True, verbose_name='Site URL')),
                ('cr', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('ecpc', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('geotargeting', models.NullBooleanField()),
                ('coupon_iframe_denied', models.NullBooleanField()),
                ('activation_date', models.DateTimeField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('avg_hold_time', models.SmallIntegerField(null=True)),
                ('show_products_links', models.NullBooleanField()),
                ('products_xml_link', models.CharField(max_length=250, null=True)),
                ('products_csv_link', models.CharField(max_length=250, null=True)),
                ('actions', models.ManyToManyField(to='admintad.MetaAction')),
                ('categories', models.ManyToManyField(to='admintad.MetaCategory')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admintad.MetaCurrency')),
                ('regions', models.ManyToManyField(to='admintad.MetaRegion')),
            ],
        ),
    ]
