# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0040_advcampaignsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaignsite',
            name='connection_status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'pending'), (3, 'declined')], null=True),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admintad.MetaCurrency'),
        ),
    ]
