# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0041_auto_20171127_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaignsite',
            name='currency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admintad.MetaCurrency'),
        ),
    ]
