# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0043_auto_20171127_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaignsite',
            name='traffics',
            field=models.ManyToManyField(to='admintad.MetaTraffic'),
        ),
    ]
