# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0044_advcampaignsite_traffics'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaignsite',
            name='goto_cookie_lifetime',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='advcampaignsite',
            name='gotolink',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='advcampaignsite',
            name='moderation',
            field=models.NullBooleanField(),
        ),
    ]
