# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0045_auto_20171127_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvCampaignRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tariff', models.CharField(max_length=250, null=True)),
                ('name_action', models.CharField(max_length=250, null=True)),
                ('size', models.CharField(max_length=250, null=True)),
                ('price_s', models.CharField(max_length=250, null=True)),
                ('is_percentage', models.NullBooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='advcampaignsite',
            options={'verbose_name_plural': 'Adv campaign sites'},
        ),
        migrations.AddField(
            model_name='advcampaignsite',
            name='rate',
            field=models.ManyToManyField(to='admintad.AdvCampaignRate'),
        ),
    ]
