# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0047_auto_20171201_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcampaignrate',
            name='hash',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
