# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0048_advcampaignrate_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaignrate',
            name='price_s',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='advcampaignrate',
            name='size',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
    ]
