# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0049_auto_20171201_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advcampaign',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='advcampaign',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='advcampaign',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='advcampaign',
            name='traffics',
        ),
        migrations.DeleteModel(
            name='CouponCategory',
        ),
        migrations.AlterModelOptions(
            name='advcampaignrate',
            options={'verbose_name_plural': 'Adv campaign rates'},
        ),
        migrations.DeleteModel(
            name='AdvCampaign',
        ),
    ]
