# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0050_auto_20171201_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advcampaignsite',
            name='rate',
        ),
        migrations.AddField(
            model_name='advcampaignsite',
            name='rates',
            field=models.ManyToManyField(to='admintad.AdvCampaignRate', verbose_name='Rates'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='actions',
            field=models.ManyToManyField(to='admintad.MetaAction', verbose_name='Actions'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='categories',
            field=models.ManyToManyField(to='admintad.MetaCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='connection_status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'pending'), (3, 'declined')], null=True, verbose_name='Connection status'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admintad.MetaCurrency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='image',
            field=models.URLField(max_length=250, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='raw_description',
            field=models.TextField(null=True, verbose_name='Raw description'),
        ),
        migrations.AlterField(
            model_name='advcampaignsite',
            name='regions',
            field=models.ManyToManyField(to='admintad.MetaRegion', verbose_name='Regions'),
        ),
    ]
