# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintad', '0051_auto_20171205_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advcampaignsite',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'disabled')], null=True, verbose_name='Status'),
        ),
    ]
